# Вторая домашняя работа

#### 2*a) Реализуйте метод Ричардсона решения системы уравнений из задачи II.10.6д. Оптимальное значение параметра 𝜏 подобрать экспериментально, основываясь на оценке скорости сходимости метода на первых 10 итерациях. При помощи степенного метода поиска максимального по модулю собственного значения оцените число обусловенности матрицы системы. Используя оценку числа обусловенности, получить решение системы с относительной точностью $\epsilon = 10^{−5}$.

Проинициализируем матрицу и вектор $B$

In [47]:
import numpy as np
M = []
b = []
for k in range(100):
    base = [0] * 100
    b.append(k+1)
    if k - 4 >= 0:
        base[k-4] = 1
    if k - 3 >= 0:
        base[k-3] = 1
    if k - 2 >= 0:
        base[k-2] = 1
    if k - 1 >= 0:
        base[k-1] = 1
    base[k] = 10
    if k + 1 < 100:
        base[k+1] = 1
    if k + 2 < 100:
        base[k+2] = 1
    if k + 3 < 100:
        base[k+3] = 1
    if k + 4 < 100:
        base[k+4] = 1
    M.append(base)
MPG = np.array(M)
MPG

array([[10,  1,  1, ...,  0,  0,  0],
       [ 1, 10,  1, ...,  0,  0,  0],
       [ 1,  1, 10, ...,  0,  0,  0],
       ...,
       [ 0,  0,  0, ..., 10,  1,  1],
       [ 0,  0,  0, ...,  1, 10,  1],
       [ 0,  0,  0, ...,  1,  1, 10]])

In [48]:
B = np.array(b)
B

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

Будем выбирать $\tau$

In [49]:
### Пусть r = 0.01
r = 0.01
x = B
for k in range(10):
    x = x - np.dot(r, np.dot(MPG, x)) + np.dot(r, B)
np.linalg.norm(B - np.dot(MPG, x))

1383.8444890464007

In [50]:
### Пусть r = 10
r = 10
x = B
for k in range(10):
    x = x - np.dot(r, np.dot(MPG, x)) + np.dot(r, B)
np.linalg.norm(B - np.dot(MPG, x))

5.552122813659337e+19

In [51]:
### Пусть r = 1
r = 1
x = B
for k in range(10):
    x = x - np.dot(r, np.dot(MPG, x)) + np.dot(r, B)
np.linalg.norm(B - np.dot(MPG, x))

1.8214815761050796e+16

In [52]:
### Пусть r = 0.1
r = 0.1
x = B
for k in range(10):
    x = x - np.dot(r, np.dot(MPG, x)) + np.dot(r, B)
np.linalg.norm(B - np.dot(MPG, x))

923.0511482091905

In [53]:
### Пусть r = 0.001
r = 0.001
x = B
for k in range(10):
    x = x - np.dot(r, np.dot(MPG, x)) + np.dot(r, B)
np.linalg.norm(B - np.dot(MPG, x))

8131.529310676209

Получаем наибольшую скорость сходимости при $\tau = 0.1$ 

Б) Воспользуемся степенным методом Поиска МаксиМального По модулю собственноГо значения:

In [54]:
import random
r = np.array([random.random() for k in range(100)])
r /= np.linalg.norm(r)
for k in range(100):
    r = np.dot(MPG, r)
    r /= np.linalg.norm(r)
r

array([0.01126776, 0.01516286, 0.01959509, 0.02456303, 0.03005691,
       0.03479703, 0.03959861, 0.04438869, 0.04909275, 0.05363661,
       0.05808951, 0.06242863, 0.06663883, 0.07071298, 0.07465205,
       0.07844903, 0.08209932, 0.08559997, 0.08894883, 0.09214372,
       0.09518335, 0.09806716, 0.10079515, 0.10336786, 0.10578641,
       0.10805246, 0.11016815, 0.1121361 , 0.11395937, 0.11564143,
       0.11718613, 0.11859767, 0.11988057, 0.12103962, 0.12207988,
       0.12300662, 0.12382527, 0.12454144, 0.12516079, 0.12568909,
       0.12613207, 0.12649548, 0.12678497, 0.12700606, 0.1271641 ,
       0.12726422, 0.12731127, 0.12730976, 0.12726385, 0.12717725,
       0.12705319, 0.12689439, 0.12670301, 0.1264806 , 0.12622806,
       0.12594562, 0.12563282, 0.12528847, 0.12491065, 0.12449672,
       0.12404326, 0.12354616, 0.12300058, 0.12240098, 0.1217412 ,
       0.12101443, 0.12021334, 0.11933008, 0.11835639, 0.11728366,
       0.11610302, 0.11480543, 0.11338181, 0.11182311, 0.11012

In [55]:
mu = np.dot(r, np.dot(MPG, r))
mu

17.970172136401555

Найдём собственные значения матрицы:

In [59]:
np.max(abs(np.linalg.eig(MPG)[0]))

17.971962983171878

Аналогично для обратной матрицы

Можно найти обратную матрицу, Пользуясь тем, что нам известно наибольшее по модулю собственное значение:

In [80]:
MPGD = MPG / (mu + mu)
MPGD

array([[0.27823885, 0.02782388, 0.02782388, ..., 0.        , 0.        ,
        0.        ],
       [0.02782388, 0.27823885, 0.02782388, ..., 0.        , 0.        ,
        0.        ],
       [0.02782388, 0.02782388, 0.27823885, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.27823885, 0.02782388,
        0.02782388],
       [0.        , 0.        , 0.        , ..., 0.02782388, 0.27823885,
        0.02782388],
       [0.        , 0.        , 0.        , ..., 0.02782388, 0.02782388,
        0.27823885]])

У полученной матрицы спектральный радиус не превосходит 0.5 Можно убедиться подсчётом миноров, что матрица Положительно определенаБ а значит и все её собственные значения Положительны. Получаем, Матрица E-MPGD имеет спектральный радиус не Более 0.5 (Можно перейти к Базису собственных векторов MPGD, там она имеет диагональный вид с Положительными числами, не превосходящими 0.5, на диагонали, а Е в любом базисе имеет диагональный вид с 1ми на диагонали) Поэтому ряд $\Sigma_{n=1}^\infty(E-MPGD)^n$ будет сходиться к $MPGD^{-1}$

In [81]:
E = []
for k in range(100):
    base = [0] * 100
    base[k] = 1
    E.append(base)
E = np.array(E)
E

array([[1, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 0, 1]])

In [82]:
ELEM = (E-MPGD)
MPGB = ELEM
for k in range(10000):
    ELEM = np.dot(ELEM, E-MPGD)
    MPGB += ELEM

И сама обратная матрица:

In [83]:
MPGB = MPGB / (mu + mu)
MPGB

array([[ 7.55211829e-02, -8.10353344e-03, -8.34491917e-03, ...,
        -4.02578041e-23,  1.58985232e-23,  2.64249869e-23],
       [-8.10353344e-03,  7.61566003e-02, -7.44918841e-03, ...,
        -1.14230305e-22, -3.93706775e-23,  1.58985232e-23],
       [-8.34491917e-03, -7.44918841e-03,  7.68304367e-02, ...,
        -1.04225509e-22, -1.14230305e-22, -4.02578041e-23],
       ...,
       [-4.02578041e-23, -1.14230305e-22, -1.04225509e-22, ...,
         7.68304367e-02, -7.44918841e-03, -8.34491917e-03],
       [ 1.58985232e-23, -3.93706775e-23, -1.14230305e-22, ...,
        -7.44918841e-03,  7.61566003e-02, -8.10353344e-03],
       [ 2.64249869e-23,  1.58985232e-23, -4.02578041e-23, ...,
        -8.34491917e-03, -8.10353344e-03,  7.55211829e-02]])

In [85]:
np.dot(MPGB, MPG)

array([[ 7.21761152e-01, -2.78238848e-02, -2.78238848e-02, ...,
        -2.58608757e-37, -2.29221398e-37, -5.87747175e-38],
       [-2.78238848e-02,  7.21761152e-01, -2.78238848e-02, ...,
         5.81869704e-37, -4.17300495e-37, -3.52648305e-38],
       [-2.78238848e-02, -2.78238848e-02,  7.21761152e-01, ...,
         0.00000000e+00,  7.52316385e-37,  2.35098870e-37],
       ...,
       [ 2.82118644e-37,  7.52316385e-37, -2.46853814e-37, ...,
         7.21761152e-01, -2.78238848e-02, -2.78238848e-02],
       [-7.05296610e-38, -2.82118644e-37,  4.70197740e-37, ...,
        -2.78238848e-02,  7.21761152e-01, -2.78238848e-02],
       [ 0.00000000e+00, -9.40395481e-38, -2.58608757e-37, ...,
        -2.78238848e-02, -2.78238848e-02,  7.21761152e-01]])

In [86]:
import random
r = np.array([random.random() for k in range(100)])
r /= np.linalg.norm(r)
for k in range(100):
    r = np.dot(MPGB, r)
    r /= np.linalg.norm(r)

In [89]:
mu0 = np.dot(np.transpose(r), np.dot(MPGB, r))
mu0 ** -1

8.692255510367122

In [92]:
min(np.linalg.eig(MPG)[0])

6.9795132834432145

Поскуольку мы работаем с евклидовой нормой, ей подчинена норма максимального собственного значенияБ и число обусловленности $\mu$ равно:

In [91]:
mu * mu0

2.067377346992251

Можно теперь получить, что оптимальное $\tau \approx \frac{\mu + 1/\mu0}{2} = $

In [93]:
(mu + mu0 ** -1) / 2

13.331213823384338

Получить решение с $\epsilon$ Можно Будет за $\mu$ * $\mu_0$ $ln(\epsilon^{-1})$

In [94]:
from math import log
mu*mu0*log(10 ** 5)

23.801561303889677

In [110]:
r = (mu + mu0 ** -1) / 2
x = B
for k in range(23):
    x = x -  (1 / r) * np.dot(MPG, x) + (1 / r) * B
np.linalg.norm(np.dot(MPG, x) - B) / np.linalg.norm(B)

1.2113952393905836e-09

Получили высокую точность за сравнительно малое число итераций